openapi: 3.0.0
info:
  title: YourSuper API
  description: This is a OpenAPI definition for the Australian Taxation Office YourSuper API
  version: 1.0.0
servers:
  - url: https://www.ato.gov.au/api/v1/YourSuper
    description: Main public server
paths:
  /APRAData:
    get:
      summary: Returns Super Products
      parameters:
        - in: header
          name: range
          schema:
            type: string
            default: items=0-9999
          required: true
          
        - in: query
          name: Filter
          schema:
            type: string
            default: "'clientIdentifierTypeCode=0,clientIdentifierValueID=0,individualAgeNumber=50,performanceRatingCode=All,privateFundsExcludedIndicator=false,retrieveAllProductsIndicator=false,superannuationIndividualAccountBalanceAmount=50000.00'"
          allowReserved: true 
          required: true
          
      responses:
        '206':
          description: OK